//// QPACK static table (RFC 9204 Appendix A).
////
//// The 99-entry table shared by every QPACK encoder/decoder. Generated
//// from the RFC 9204 Appendix A table text (do not hand-edit entries;
//// regenerate from the RFC if this ever needs to change).

/// The result of looking up a name/value pair against the static table.
///
pub type Match {
  /// Both the name and the value matched a static entry.
  FullMatch(index: Int)
  /// Only the name matched a static entry (the first such entry).
  NameMatch(index: Int)
  /// Neither the name nor the value matched any static entry.
  NoMatch
}

/// Looks up the (name, value) pair at a static table index.
///
/// Returns `Error(Nil)` if `index` is outside the static table (0-98).
///
pub fn entry(index: Int) -> Result(#(String, String), Nil) {
  case index {
    0 -> Ok(#(":authority", ""))
    1 -> Ok(#(":path", "/"))
    2 -> Ok(#("age", "0"))
    3 -> Ok(#("content-disposition", ""))
    4 -> Ok(#("content-length", "0"))
    5 -> Ok(#("cookie", ""))
    6 -> Ok(#("date", ""))
    7 -> Ok(#("etag", ""))
    8 -> Ok(#("if-modified-since", ""))
    9 -> Ok(#("if-none-match", ""))
    10 -> Ok(#("last-modified", ""))
    11 -> Ok(#("link", ""))
    12 -> Ok(#("location", ""))
    13 -> Ok(#("referer", ""))
    14 -> Ok(#("set-cookie", ""))
    15 -> Ok(#(":method", "CONNECT"))
    16 -> Ok(#(":method", "DELETE"))
    17 -> Ok(#(":method", "GET"))
    18 -> Ok(#(":method", "HEAD"))
    19 -> Ok(#(":method", "OPTIONS"))
    20 -> Ok(#(":method", "POST"))
    21 -> Ok(#(":method", "PUT"))
    22 -> Ok(#(":scheme", "http"))
    23 -> Ok(#(":scheme", "https"))
    24 -> Ok(#(":status", "103"))
    25 -> Ok(#(":status", "200"))
    26 -> Ok(#(":status", "304"))
    27 -> Ok(#(":status", "404"))
    28 -> Ok(#(":status", "503"))
    29 -> Ok(#("accept", "*/*"))
    30 -> Ok(#("accept", "application/dns-message"))
    31 -> Ok(#("accept-encoding", "gzip, deflate, br"))
    32 -> Ok(#("accept-ranges", "bytes"))
    33 -> Ok(#("access-control-allow-headers", "cache-control"))
    34 -> Ok(#("access-control-allow-headers", "content-type"))
    35 -> Ok(#("access-control-allow-origin", "*"))
    36 -> Ok(#("cache-control", "max-age=0"))
    37 -> Ok(#("cache-control", "max-age=2592000"))
    38 -> Ok(#("cache-control", "max-age=604800"))
    39 -> Ok(#("cache-control", "no-cache"))
    40 -> Ok(#("cache-control", "no-store"))
    41 -> Ok(#("cache-control", "public, max-age=31536000"))
    42 -> Ok(#("content-encoding", "br"))
    43 -> Ok(#("content-encoding", "gzip"))
    44 -> Ok(#("content-type", "application/dns-message"))
    45 -> Ok(#("content-type", "application/javascript"))
    46 -> Ok(#("content-type", "application/json"))
    47 -> Ok(#("content-type", "application/x-www-form-urlencoded"))
    48 -> Ok(#("content-type", "image/gif"))
    49 -> Ok(#("content-type", "image/jpeg"))
    50 -> Ok(#("content-type", "image/png"))
    51 -> Ok(#("content-type", "text/css"))
    52 -> Ok(#("content-type", "text/html; charset=utf-8"))
    53 -> Ok(#("content-type", "text/plain"))
    54 -> Ok(#("content-type", "text/plain;charset=utf-8"))
    55 -> Ok(#("range", "bytes=0-"))
    56 -> Ok(#("strict-transport-security", "max-age=31536000"))
    57 ->
      Ok(#("strict-transport-security", "max-age=31536000; includesubdomains"))
    58 ->
      Ok(#(
        "strict-transport-security",
        "max-age=31536000; includesubdomains; preload",
      ))
    59 -> Ok(#("vary", "accept-encoding"))
    60 -> Ok(#("vary", "origin"))
    61 -> Ok(#("x-content-type-options", "nosniff"))
    62 -> Ok(#("x-xss-protection", "1; mode=block"))
    63 -> Ok(#(":status", "100"))
    64 -> Ok(#(":status", "204"))
    65 -> Ok(#(":status", "206"))
    66 -> Ok(#(":status", "302"))
    67 -> Ok(#(":status", "400"))
    68 -> Ok(#(":status", "403"))
    69 -> Ok(#(":status", "421"))
    70 -> Ok(#(":status", "425"))
    71 -> Ok(#(":status", "500"))
    72 -> Ok(#("accept-language", ""))
    73 -> Ok(#("access-control-allow-credentials", "FALSE"))
    74 -> Ok(#("access-control-allow-credentials", "TRUE"))
    75 -> Ok(#("access-control-allow-headers", "*"))
    76 -> Ok(#("access-control-allow-methods", "get"))
    77 -> Ok(#("access-control-allow-methods", "get, post, options"))
    78 -> Ok(#("access-control-allow-methods", "options"))
    79 -> Ok(#("access-control-expose-headers", "content-length"))
    80 -> Ok(#("access-control-request-headers", "content-type"))
    81 -> Ok(#("access-control-request-method", "get"))
    82 -> Ok(#("access-control-request-method", "post"))
    83 -> Ok(#("alt-svc", "clear"))
    84 -> Ok(#("authorization", ""))
    85 ->
      Ok(#(
        "content-security-policy",
        "script-src 'none'; object-src 'none'; base-uri 'none'",
      ))
    86 -> Ok(#("early-data", "1"))
    87 -> Ok(#("expect-ct", ""))
    88 -> Ok(#("forwarded", ""))
    89 -> Ok(#("if-range", ""))
    90 -> Ok(#("origin", ""))
    91 -> Ok(#("purpose", "prefetch"))
    92 -> Ok(#("server", ""))
    93 -> Ok(#("timing-allow-origin", "*"))
    94 -> Ok(#("upgrade-insecure-requests", "1"))
    95 -> Ok(#("user-agent", ""))
    96 -> Ok(#("x-forwarded-for", ""))
    97 -> Ok(#("x-frame-options", "deny"))
    98 -> Ok(#("x-frame-options", "sameorigin"))
    _ -> Error(Nil)
  }
}

/// Finds the best static table match for a (name, value) pair.
///
/// Returns `FullMatch` if some entry has both the same name and value,
/// else `NameMatch` with the first entry whose name matches, else
/// `NoMatch`.
///
pub fn find(name: String, value: String) -> Match {
  case find_full(name, value) {
    Ok(index) -> FullMatch(index)
    Error(Nil) ->
      case find_name(name) {
        Ok(index) -> NameMatch(index)
        Error(Nil) -> NoMatch
      }
  }
}

fn find_full(name: String, value: String) -> Result(Int, Nil) {
  case name, value {
    ":authority", "" -> Ok(0)
    ":path", "/" -> Ok(1)
    "age", "0" -> Ok(2)
    "content-disposition", "" -> Ok(3)
    "content-length", "0" -> Ok(4)
    "cookie", "" -> Ok(5)
    "date", "" -> Ok(6)
    "etag", "" -> Ok(7)
    "if-modified-since", "" -> Ok(8)
    "if-none-match", "" -> Ok(9)
    "last-modified", "" -> Ok(10)
    "link", "" -> Ok(11)
    "location", "" -> Ok(12)
    "referer", "" -> Ok(13)
    "set-cookie", "" -> Ok(14)
    ":method", "CONNECT" -> Ok(15)
    ":method", "DELETE" -> Ok(16)
    ":method", "GET" -> Ok(17)
    ":method", "HEAD" -> Ok(18)
    ":method", "OPTIONS" -> Ok(19)
    ":method", "POST" -> Ok(20)
    ":method", "PUT" -> Ok(21)
    ":scheme", "http" -> Ok(22)
    ":scheme", "https" -> Ok(23)
    ":status", "103" -> Ok(24)
    ":status", "200" -> Ok(25)
    ":status", "304" -> Ok(26)
    ":status", "404" -> Ok(27)
    ":status", "503" -> Ok(28)
    "accept", "*/*" -> Ok(29)
    "accept", "application/dns-message" -> Ok(30)
    "accept-encoding", "gzip, deflate, br" -> Ok(31)
    "accept-ranges", "bytes" -> Ok(32)
    "access-control-allow-headers", "cache-control" -> Ok(33)
    "access-control-allow-headers", "content-type" -> Ok(34)
    "access-control-allow-origin", "*" -> Ok(35)
    "cache-control", "max-age=0" -> Ok(36)
    "cache-control", "max-age=2592000" -> Ok(37)
    "cache-control", "max-age=604800" -> Ok(38)
    "cache-control", "no-cache" -> Ok(39)
    "cache-control", "no-store" -> Ok(40)
    "cache-control", "public, max-age=31536000" -> Ok(41)
    "content-encoding", "br" -> Ok(42)
    "content-encoding", "gzip" -> Ok(43)
    "content-type", "application/dns-message" -> Ok(44)
    "content-type", "application/javascript" -> Ok(45)
    "content-type", "application/json" -> Ok(46)
    "content-type", "application/x-www-form-urlencoded" -> Ok(47)
    "content-type", "image/gif" -> Ok(48)
    "content-type", "image/jpeg" -> Ok(49)
    "content-type", "image/png" -> Ok(50)
    "content-type", "text/css" -> Ok(51)
    "content-type", "text/html; charset=utf-8" -> Ok(52)
    "content-type", "text/plain" -> Ok(53)
    "content-type", "text/plain;charset=utf-8" -> Ok(54)
    "range", "bytes=0-" -> Ok(55)
    "strict-transport-security", "max-age=31536000" -> Ok(56)
    "strict-transport-security", "max-age=31536000; includesubdomains" -> Ok(57)
    "strict-transport-security", "max-age=31536000; includesubdomains; preload"
    -> Ok(58)
    "vary", "accept-encoding" -> Ok(59)
    "vary", "origin" -> Ok(60)
    "x-content-type-options", "nosniff" -> Ok(61)
    "x-xss-protection", "1; mode=block" -> Ok(62)
    ":status", "100" -> Ok(63)
    ":status", "204" -> Ok(64)
    ":status", "206" -> Ok(65)
    ":status", "302" -> Ok(66)
    ":status", "400" -> Ok(67)
    ":status", "403" -> Ok(68)
    ":status", "421" -> Ok(69)
    ":status", "425" -> Ok(70)
    ":status", "500" -> Ok(71)
    "accept-language", "" -> Ok(72)
    "access-control-allow-credentials", "FALSE" -> Ok(73)
    "access-control-allow-credentials", "TRUE" -> Ok(74)
    "access-control-allow-headers", "*" -> Ok(75)
    "access-control-allow-methods", "get" -> Ok(76)
    "access-control-allow-methods", "get, post, options" -> Ok(77)
    "access-control-allow-methods", "options" -> Ok(78)
    "access-control-expose-headers", "content-length" -> Ok(79)
    "access-control-request-headers", "content-type" -> Ok(80)
    "access-control-request-method", "get" -> Ok(81)
    "access-control-request-method", "post" -> Ok(82)
    "alt-svc", "clear" -> Ok(83)
    "authorization", "" -> Ok(84)
    "content-security-policy",
      "script-src 'none'; object-src 'none'; base-uri 'none'"
    -> Ok(85)
    "early-data", "1" -> Ok(86)
    "expect-ct", "" -> Ok(87)
    "forwarded", "" -> Ok(88)
    "if-range", "" -> Ok(89)
    "origin", "" -> Ok(90)
    "purpose", "prefetch" -> Ok(91)
    "server", "" -> Ok(92)
    "timing-allow-origin", "*" -> Ok(93)
    "upgrade-insecure-requests", "1" -> Ok(94)
    "user-agent", "" -> Ok(95)
    "x-forwarded-for", "" -> Ok(96)
    "x-frame-options", "deny" -> Ok(97)
    "x-frame-options", "sameorigin" -> Ok(98)
    _, _ -> Error(Nil)
  }
}

fn find_name(name: String) -> Result(Int, Nil) {
  case name {
    ":authority" -> Ok(0)
    ":path" -> Ok(1)
    "age" -> Ok(2)
    "content-disposition" -> Ok(3)
    "content-length" -> Ok(4)
    "cookie" -> Ok(5)
    "date" -> Ok(6)
    "etag" -> Ok(7)
    "if-modified-since" -> Ok(8)
    "if-none-match" -> Ok(9)
    "last-modified" -> Ok(10)
    "link" -> Ok(11)
    "location" -> Ok(12)
    "referer" -> Ok(13)
    "set-cookie" -> Ok(14)
    ":method" -> Ok(15)
    ":scheme" -> Ok(22)
    ":status" -> Ok(24)
    "accept" -> Ok(29)
    "accept-encoding" -> Ok(31)
    "accept-ranges" -> Ok(32)
    "access-control-allow-headers" -> Ok(33)
    "access-control-allow-origin" -> Ok(35)
    "cache-control" -> Ok(36)
    "content-encoding" -> Ok(42)
    "content-type" -> Ok(44)
    "range" -> Ok(55)
    "strict-transport-security" -> Ok(56)
    "vary" -> Ok(59)
    "x-content-type-options" -> Ok(61)
    "x-xss-protection" -> Ok(62)
    "accept-language" -> Ok(72)
    "access-control-allow-credentials" -> Ok(73)
    "access-control-allow-methods" -> Ok(76)
    "access-control-expose-headers" -> Ok(79)
    "access-control-request-headers" -> Ok(80)
    "access-control-request-method" -> Ok(81)
    "alt-svc" -> Ok(83)
    "authorization" -> Ok(84)
    "content-security-policy" -> Ok(85)
    "early-data" -> Ok(86)
    "expect-ct" -> Ok(87)
    "forwarded" -> Ok(88)
    "if-range" -> Ok(89)
    "origin" -> Ok(90)
    "purpose" -> Ok(91)
    "server" -> Ok(92)
    "timing-allow-origin" -> Ok(93)
    "upgrade-insecure-requests" -> Ok(94)
    "user-agent" -> Ok(95)
    "x-forwarded-for" -> Ok(96)
    "x-frame-options" -> Ok(97)
    _ -> Error(Nil)
  }
}
